-- 100 IQ questions seed
INSERT INTO questions (category, question_text, option_a, option_b, option_c, option_d, correct_answer) VALUES
('Pattern Recognition','What number comes next: 2, 4, 8, 16, ?','24','32','30','20','B'),
('Pattern Recognition','Find the next: 1, 1, 2, 3, 5, 8, ?','11','12','13','14','C'),
('Pattern Recognition','Next in series: 3, 9, 27, 81, ?','162','243','216','324','B'),
('Pattern Recognition','Next: 5, 10, 20, 40, ?','60','70','80','100','C'),
('Pattern Recognition','Next: 2, 6, 12, 20, 30, ?','40','42','44','48','B'),
('Pattern Recognition','Next: 1, 4, 9, 16, 25, ?','30','36','35','49','B'),
('Pattern Recognition','Next: 7, 14, 28, 56, ?','84','112','98','100','B'),
('Pattern Recognition','Next letter: A, C, E, G, ?','H','I','J','K','B'),
('Pattern Recognition','Next: Z, Y, X, W, ?','U','V','T','S','B'),
('Pattern Recognition','Next: 100, 81, 64, 49, ?','36','35','42','40','A'),
('Pattern Recognition','Next: 2, 3, 5, 7, 11, ?','12','13','14','15','B'),
('Pattern Recognition','Next pair: AB, CD, EF, ?','GH','FG','HI','IJ','A'),
('Pattern Recognition','Next: 1, 8, 27, 64, ?','100','125','144','216','B'),
('Pattern Recognition','Next: 4, 9, 16, 25, 36, ?','49','42','45','48','A'),
('Pattern Recognition','Next: 2, 5, 10, 17, 26, ?','35','37','36','39','B'),
('Pattern Recognition','Next: 1, 3, 6, 10, 15, ?','20','21','22','24','B'),
('Pattern Recognition','Next: 11, 22, 33, 44, ?','54','55','56','66','B'),
('Pattern Recognition','Next: 1, 2, 4, 7, 11, ?','15','16','17','18','B'),
('Pattern Recognition','Next letter: B, D, G, K, ?','O','P','Q','N','B'),
('Pattern Recognition','Next: 9, 16, 25, 36, ?','42','49','45','48','B'),
('Numerical Reasoning','If 5x = 45, what is x?','7','8','9','10','C'),
('Numerical Reasoning','12% of 250 equals?','25','30','35','40','B'),
('Numerical Reasoning','A train travels 60 km in 1.5 hours. Avg speed?','35 km/h','40 km/h','45 km/h','50 km/h','B'),
('Numerical Reasoning','If a shirt costs $80 after a 20% discount, original price?','$96','$100','$110','$120','B'),
('Numerical Reasoning','Sum of angles in a triangle?','90','180','270','360','B'),
('Numerical Reasoning','Square root of 144?','10','11','12','14','C'),
('Numerical Reasoning','2/5 of 200?','60','70','80','90','C'),
('Numerical Reasoning','If 3a = 21, then a + 5 = ?','10','11','12','13','C'),
('Numerical Reasoning','A circle has radius 7. Area? (π≈22/7)','132','144','154','164','C'),
('Numerical Reasoning','15 × 12 = ?','170','180','190','200','B'),
('Numerical Reasoning','LCM of 6 and 8?','18','20','24','48','C'),
('Numerical Reasoning','If 4 pens cost $12, what do 9 pens cost?','$24','$25','$27','$30','C'),
('Numerical Reasoning','Compound interest on $1000 at 10% for 2 years?','$200','$210','$220','$240','B'),
('Numerical Reasoning','Average of 4, 8, 12, 16, 20?','10','12','14','16','B'),
('Numerical Reasoning','If x + 7 = 15, then 2x = ?','14','16','18','20','B'),
('Numerical Reasoning','25% of 80?','15','18','20','22','C'),
('Numerical Reasoning','Ratio 12:18 simplified?','1:2','2:3','3:4','4:5','B'),
('Numerical Reasoning','Speed = distance/time. 150 km in 3 h?','40','45','50','55','C'),
('Numerical Reasoning','If 2^x = 32, x = ?','3','4','5','6','C'),
('Numerical Reasoning','8! / 7! = ?','7','8','9','56','B'),
('Verbal Reasoning','Choose the synonym of ''Abundant'':','Scarce','Plentiful','Tiny','Weak','B'),
('Verbal Reasoning','Antonym of ''Benevolent'':','Kind','Cruel','Generous','Gentle','B'),
('Verbal Reasoning','Choose the synonym of ''Diligent'':','Lazy','Hardworking','Careless','Slow','B'),
('Verbal Reasoning','Antonym of ''Transparent'':','Clear','Opaque','Plain','Visible','B'),
('Verbal Reasoning','''Book'' is to ''Reading'' as ''Fork'' is to:','Drawing','Writing','Eating','Stirring','C'),
('Verbal Reasoning','''Doctor'' is to ''Hospital'' as ''Teacher'' is to:','Office','School','Court','Studio','B'),
('Verbal Reasoning','Choose the odd one out:','Apple','Banana','Carrot','Mango','C'),
('Verbal Reasoning','Synonym of ''Candid'':','Honest','Sneaky','Quiet','Bold','A'),
('Verbal Reasoning','Antonym of ''Frugal'':','Cheap','Wasteful','Saving','Modest','B'),
('Verbal Reasoning','''Pen'' is to ''Write'' as ''Knife'' is to:','Stab','Cut','Hold','Lift','B'),
('Verbal Reasoning','Synonym of ''Lucid'':','Confusing','Clear','Dark','Heavy','B'),
('Verbal Reasoning','Choose the correct spelling:','Recieve','Receive','Receeve','Receve','B'),
('Verbal Reasoning','Plural of ''Mouse'' (animal):','Mouses','Mice','Mices','Mouse','B'),
('Verbal Reasoning','Antonym of ''Optimistic'':','Hopeful','Pessimistic','Cheerful','Positive','B'),
('Verbal Reasoning','Synonym of ''Meticulous'':','Careless','Careful','Quick','Bored','B'),
('Verbal Reasoning','''Cold'' is to ''Hot'' as ''Dark'' is to:','Night','Shadow','Bright','Dim','C'),
('Verbal Reasoning','Odd one out:','Square','Triangle','Circle','Cube','D'),
('Verbal Reasoning','Synonym of ''Vivid'':','Dull','Bright','Plain','Quiet','B'),
('Verbal Reasoning','Antonym of ''Ancient'':','Old','Modern','Aged','Antique','B'),
('Verbal Reasoning','Choose correct: ''She ___ to school every day.''','go','goes','gone','going','B'),
('Logical Reasoning','All roses are flowers. Some flowers fade quickly. Therefore:','All roses fade quickly','Some roses may fade quickly','No roses fade','All flowers are roses','B'),
('Logical Reasoning','If today is Monday, what day will it be 100 days later?','Tuesday','Wednesday','Thursday','Friday','B'),
('Logical Reasoning','A is taller than B. B is taller than C. Who is shortest?','A','B','C','Cannot tell','C'),
('Logical Reasoning','If all Bloops are Razzies and some Razzies are Lazzies, then:','All Bloops are Lazzies','Some Bloops may be Lazzies','No Bloops are Lazzies','All Lazzies are Bloops','B'),
('Logical Reasoning','In a code, CAT = 3-1-20. What is DOG?','4-15-7','4-14-7','3-15-7','4-15-8','A'),
('Logical Reasoning','If +means×, ×means−, −means÷, ÷means+: 10+5×2−1÷3=?','50','51','49','55','B'),
('Logical Reasoning','Find odd: 121, 144, 169, 196, 220','121','169','196','220','D'),
('Logical Reasoning','Statement: All cats are animals. All animals breathe. Conclusion?','All cats breathe','Some cats do not breathe','No cats breathe','Some animals are cats only','A'),
('Logical Reasoning','If Monday is the 1st, what day is the 15th?','Sunday','Monday','Tuesday','Wednesday','B'),
('Logical Reasoning','Five friends sit in a row. A is left of B but right of C. Who is leftmost?','A','B','C','Cannot tell','C'),
('Logical Reasoning','Which is true? ''Some doctors are tall'' implies:','All doctors are tall','No doctor is short','At least one doctor is tall','All tall people are doctors','C'),
('Logical Reasoning','If 2 workers build a wall in 6 days, 3 workers take:','3 days','4 days','5 days','6 days','B'),
('Logical Reasoning','Pointing to a man, Riya said ''He is my mother''s brother''s son.'' How related?','Brother','Cousin','Uncle','Nephew','B'),
('Logical Reasoning','Find missing: 6, 11, ?, 27, 38','17','18','19','20','B'),
('Logical Reasoning','Which doesn''t belong: Dog, Cat, Lion, Eagle?','Dog','Cat','Lion','Eagle','D'),
('Logical Reasoning','If A=1,B=2,...Z=26, BAD = ?','6','7','8','9','B'),
('Logical Reasoning','All squares are rectangles. Some rectangles are red. Therefore:','All squares are red','Some squares are red','Some squares may be red','No squares are red','C'),
('Logical Reasoning','If the day before yesterday was Thursday, today is:','Friday','Saturday','Sunday','Monday','B'),
('Logical Reasoning','Find the missing letter: A, D, G, J, ?','K','L','M','N','C'),
('Logical Reasoning','Odd one out: 3, 5, 11, 14, 17','3','11','14','17','C'),
('Analytical Thinking','A clock shows 3:15. Angle between the hands?','0°','7.5°','15°','22.5°','B'),
('Analytical Thinking','Five people shake hands once. Total handshakes?','8','9','10','12','C'),
('Analytical Thinking','A cube has how many edges?','6','8','10','12','D'),
('Analytical Thinking','If you fold a square paper twice, how many smaller squares?','2','3','4','8','C'),
('Analytical Thinking','Maximum slices from 3 straight cuts of a pizza?','6','7','8','9','B'),
('Analytical Thinking','A bat and ball cost $1.10. Bat costs $1 more than ball. Ball costs?','$0.10','$0.05','$0.15','$0.20','B'),
('Analytical Thinking','A rope burns in 60 minutes unevenly. How to measure 45 min with two ropes?','Light one end of both','Light both ends of one, one end of the other','Light all ends','Cannot be done','B'),
('Analytical Thinking','There are 3 light switches outside a room. Only one controls the bulb inside. With one entry, how to find it?','Use timing of heat','Random guess','Ask someone','Impossible','A'),
('Analytical Thinking','How many 3-digit numbers are divisible by 5?','180','179','100','200','A'),
('Analytical Thinking','A snail climbs 3 ft by day, slips 2 ft by night. Days to reach 10 ft?','7','8','9','10','B'),
('Analytical Thinking','Sum of first 10 natural numbers?','45','50','55','60','C'),
('Analytical Thinking','If a car covers 240 km in 4 h, time for 600 km at same speed?','8 h','9 h','10 h','12 h','C'),
('Analytical Thinking','How many diagonals in a hexagon?','6','7','8','9','D'),
('Analytical Thinking','A tank fills in 6 h, empties in 8 h. Time to fill with both open?','12 h','18 h','24 h','36 h','C'),
('Analytical Thinking','Probability of rolling a 6 on a fair die?','1/2','1/3','1/4','1/6','D'),
('Analytical Thinking','If 4 men do a job in 12 days, 6 men take?','6','8','9','10','B'),
('Analytical Thinking','How many palindromic 3-digit numbers exist?','80','90','100','110','B'),
('Analytical Thinking','In a room of 23 people, probability two share birthday is closest to:','10%','25%','50%','75%','C'),
('Analytical Thinking','A fair coin flipped 3 times. P(exactly 2 heads)?','1/8','1/4','3/8','1/2','C'),
('Analytical Thinking','Maximum number of regions a circle can be divided into by 4 chords?','8','10','11','12','C');
